// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PArcial1_ap1_2017_0485.DAL;

namespace PArcial1_ap1_2017_0485.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210209014938_Migracion_Parcial1")]
    partial class Migracion_Parcial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PArcial1_ap1_2017_0485.Entidades.Ciudades", b =>
                {
                    b.Property<int>("CuidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("CuidadId");

                    b.ToTable("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
